;;; transient-dwim-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from transient-dwim.el

 (autoload 'transient-dwim-dispatch "transient-dwim" nil t)
(register-definition-prefixes "transient-dwim" '("transient-dwim-"))

;;; End of scraped data

(provide 'transient-dwim-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; transient-dwim-autoloads.el ends here
