#!/bin/env bash

FG=#fc6d8c
BG=#5d0c5e
DZEN2=/bin/dzen2
SEPARATOR="|"
D_ICON=""
U_ICON=""
T_ICON=""
refresh=$(watch -n 1)

#echo $(date)
while true; do echo $SEPARATOR $(curl wttr.in/Brazil?format=3) $SEPARATOR $T_ICON $(uptime -p) $SEPARATOR $U_ICON $USER $SEPARATOR $D_ICON $(watch -n 1 date) $SEPARATOR
	       sleep 20
	       
done | dzen2 -x 85 -y 877 -w 1400 -p -ta r -fg $FG -bg $BG 	       


 
