icons_format = "{icon}"

[theme]
theme = "bad-wolf"
[theme.overrides]
idle_bg = "#151617"
idle_fg = "#f73156"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "




[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20,rot_interval:0.5) $play $next |}"
interface_name_exclude = [".*kdeconnect.*", "mpd"]
[block.theme_overrides]
info_bg = "#151617"
info_fg = "#f73156"
idle_bg = "#151617"
idle_fg = "#f73156"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 30
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "
[block.theme_overrides]
idle_bg = "#eb4034"
idle_fg = "#000000"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
idle_bg = "#eb4034"
idle_fg = "0000000"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "time"
interval = 10
format = " $timestamp.datetime(f:'%a %d/%m %R') "
[block.theme_overrides]
idle_bg = "#eb4034"
idle_fg = "0000000"

[[block]]
block = "menu"
text = "\uf011"
[[block.items]]
display = " -&gt;   Sleep   &lt;-"
cmd = "systemctl suspend"
[[block.items]]
display = " -&gt; Power Off &lt;-"
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " -&gt;  Reboot   &lt;-"
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"


