print("sane")
print "sane"
print ("sane")
(print "sane")
exit
(defun salve (nome)
	 "Exibe uma saudacao para NOME"
	 (message "Salve, %s!" nome))
(defun Thiago (nome)
	 "Exibe uma saudacao para NOME."
	 (message "Salve, %s!"))
(defun Thiago (nome)
	 "Exibe uma saudacao para NOME"
	 (message "Salve, %s!" nome))
(defun Thiago (nome)
	 "Exibe uma saudacao pra blah blah blah."
	 (print "Salve, %s!" nome))
nil
()
`()
